---
title: "eds-212-day-2-tasks"
format: html
editor: visual
---

## Day 2 end of day tasks

```{r}
library(tidyverse)
library(palmerpenguins)
```

### Section 3 tasks:

```{r}
# ---TASK A---
## assign function

fx_task <- expression(x^2)

## assign derivative

dfdx_task <- D(fx_task, 'x')

## assign x value

x = 3

## evaluate derivative

eval(dfdx_task)
```

```{r}
#---TASKB---
## assign function

Pa <- expression(2 * (3 * a + 2)^4 - 5)

## assign derivative 

dPda <- D(Pa, 'a')

## assign a value

a = 1.2

## evaluate derivative at assigned a value

eval(dPda)
```

### Section 4 tasks

```{r}
# make a plot of bill length and bill depth
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point() +
  scale_color_manual(values=c('darkseagreen3','dodgerblue2','plum'),
                       guide=FALSE) +
  labs(title = "Palmer Penguin Bill Length and Depth", x = "Bill Length (mm)", y = "Bill Depth (mm)") +
  theme_light() + 
  theme(plot.margin = unit(c(0.25, 0.25, 0.25, 0.25),
                                "inches"))

```

```{r}
# Jitter stuff
ggplot(penguins, aes(species, flipper_length_mm, color = species)) +
  geom_jitter() + 
  labs(title = "Jitter plot of species and flipper length", x = "Species", y = "Flipper Length (mm)") +
  scale_color_manual(values=c('pink','palegreen3','cornflowerblue'),
                       guide=FALSE) +
  theme_light() + 
  theme(plot.margin = unit(c(0.25, 0.25, 0.25, 0.25), "inches"))

```
