---
title: "eds212_day2_session2"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(palmerpenguins)
```

## Plotting functions in ggplot2

```{r}
# create a function

fx <- function(x) {3 * x^2 + 4}

# plot the function

ggplot(data.frame(x = c(1, 100)), aes(x = x)) + 
  geom_function(fun = fx, color = "palegreen3") +
  theme_light() +
  labs(title = "Plotting a Function") +
  theme(plot.margin = unit(c(0.25, 0.25, 0.25, 0.25),
                                "inches"))
```

## Partial derivative

```{r}
# use expression so we can take the derivative

fxyz <- expression(2 * x * y + 3 * x^2 * z^3)

# take partial derivative in respect to y

dfdy <- D(fxyz, 'y') 
```

## Penguins plot

```{r}
ggplot(data = penguins, aes(x = body_mass_g, y = flipper_length_mm)) + 
  geom_point(color = "steelblue3") +
  labs(title = "Body Mass vs. Flipper Length", x = "Body Mass (g)", y = "Flipper Length (mm)") + 
  theme_light() + 
  theme(plot.margin = unit(c(0.25, 0.25, 0.25, 0.25),
                                "inches"))
```
